### ISSUE TITLE
Missing Energy Prod/Demand after loading a save

### ISSUE THREAD

**Issue by ElPadredesNurgles** [Keranik/COI-Extended#10]
[24-04-08_01-33-autosave.zip](https://github.com/Keranik/COI-Extended/files/14910632/24-04-08_01-33-autosave.zip)
Tried to play with full package yesterday and it worked well and nice, but somehow I'm having problems with loading my saves today- they all get 0/0 energy prod/demand with 52MW of possible production and all my belts,are halted because of it. Energy both from diesel gens and steam turbines with several small battery banks.

**Comment by Keranik** [comment]
I'm working on a fix for this now thanks

**Comment by Keranik** [comment]
This should be fixed now in 63, please download the latest version, if you are upgrading you only need to get the DLL only files.  Thanks for your report.
