### ISSUE TITLE
COI Extended cant load

### ISSUE THREAD

**Issue by IndigoWing** [Keranik/COI-Extended#11]
in 0.6.0d update (24/04/09) , game cant load mod COI Extended
error report is that
Failed to load the mod
Exception has been thrown by the target of an invocation.

**Comment by Keranik** [comment]
You need to update to latest game version as it made some changes that have to do with modding and the mod needed to be updated as a result.

**Comment by Burki96** [comment]
> d

No, the game updated just today and broke loading the mod.

**Comment by Burki96** [comment]
> You need to update to latest game version as it made some changes that have to do with modding and the mod needed to be updated as a result.

No, the game updated just today and broke the mod loading

**Comment by Burki96** [comment]
Never mind, just noticed the update on github

**Comment by IndigoWing** [comment]
oh ,thx i just see that mod updated 3h ago
