### ISSUE TITLE
no recipe in the fishing dock

### ISSUE THREAD

**Issue by DevelopmentAnything** [Keranik/COI-Extended#12]
![image](https://github.com/Keranik/COI-Extended/assets/110871727/9cce4cc6-c6db-4194-bedb-69d430ec2b4a)

![image](https://github.com/Keranik/COI-Extended/assets/110871727/d42cd9ce-8efe-4959-9843-d58b413fd97f)

fishing area is inactive.

I've **completed the research**, but the recipe is locked.

**Comment by Keranik** [comment]
Can you reproduce this? I cannot.

**Comment by DevelopmentAnything** [comment]
Always.

i use COIExtended, COIExtended.ItemSink
not use COIExtended.Cheats

new game has a recipe, but old game doesn't. need to double check the existing research status.

![image](https://github.com/Keranik/COI-Extended/assets/110871727/5e18c001-d486-411e-81c1-df30cb2f6989)

**Comment by AlexBig101** [comment]
Works great. I haven’t tried it with fish additives yet. At least the recipes are active.

**Comment by AlexBig101** [comment]
In the second screenshot, the shore is covered in garbage. There is nowhere to put it somewhere else, it needs to be thrown into the sea ?? Game is game, but.....

**Comment by DevelopmentAnything** [comment]
@AlexBig101 
I clearly wrote down the reason.
The reason you say normal is because you started a new game.
I'm just reaffirming the completed research on the existing game and saying that the recipe needs to be updated.

**Comment by DevelopmentAnything** [comment]
@AlexBig101
This page is where report problems, track and fix causes. Just because one person is normal, throw away the prejudice that everyone else should be normal.
I think it's important to make exceptions to prevent errors from occurring in any situation. That's why there are if statements, try~catch statements in the code.

**Comment by Keranik** [comment]
I'm looking to see if I can recreate this, I will fix it if I can.

**Comment by Keranik** [comment]
Okay I've re-created this and it is fixed in the next patch, thanks for letting me know!

**Comment by Keranik** [comment]
I also added a command if you've been affected by this issue unlock_fishing in console will give you the recipes

next patch
