### ISSUE TITLE
COIExtended throws exception, preventing loading.

### ISSUE THREAD

**Issue by philomelus** [Keranik/COI-Extended#14]
Using the suite, and the other two included mods work fine.  This is on v0.6.0d.

**Comment by ttr** [comment]
2nd that, however game logs do not show any exeption for me.
comparing logs from before update, seems that Harmony patching is not happeing.

**Comment by Keranik** [comment]
Post a screenshot of your menu with the mods list

**Comment by philomelus** [comment]
This is what Copy Error button puts into clipboard:

"Failed to load the mod
Exception has been thrown by the target of an invocation."

I will add the screenshot as soon as I remember how :-)

**Comment by philomelus** [comment]
Here it is.  Just didn't see the "Paste, drop ..." note at the bottom.

![Capture](https://github.com/Keranik/COI-Extended/assets/42464919/8310d219-a30e-4e17-9548-42b91dd2165e)

**Comment by Keranik** [comment]
Well all you need to do is simply download the latest version of the mod

![image](https://github.com/Keranik/COI-Extended/assets/137360086/81933410-1e56-4194-8101-8f0952d1b58a)

**Comment by Keranik** [comment]
The developers made an update which changes the way mods are loaded and the mod needed to be updated to accommodate that.

**Comment by philomelus** [comment]
It loads now.  Thanks for the fast handling of this!

**Comment by Keranik** [comment]
Enjoy!

**Comment by ttr** [comment]
> Well all you need to do is simply download the latest version of the mod
> 
> ![image](https://private-user-images.githubusercontent.com/137360086/320847563-81933410-1e56-4194-8101-8f0952d1b58a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NzMyNDUsIm5iZiI6MTcxMjY3Mjk0NSwicGF0aCI6Ii8xMzczNjAwODYvMzIwODQ3NTYzLTgxOTMzNDEwLTFlNTYtNDE5NC04MTAxLThmMDk1MmQxYjU4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQxNDI5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDM4ZDJiMjc2MmM3ZmFmY2QyNTliOWUyZWRjZTc5NjQ0NjgzMzdmYjFmYmIyODY1MWVkM2U4YTU3YjQ2YTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4eTNwiU7FlILLNZASAHYC8tLCVnwo6QzJY6ezSZa3lo)

Ah,
I saw that last release was 4 days ago so though there was no update but I saw you did re-upload attachments.

Thanks.
