### ISSUE TITLE
COIExtended.Cheat Single selection for God mode storage and custom tool cursor

### ISSUE THREAD

**Issue by DavidNeuschl** [Keranik/COI-Extended#15]
Would it be possible to add a single selection (one-click on entity as alternative to only dragging and selecting) with highlight of storage upon hovering over storage, similar to unity tool. With different outline color (maybe blue to complement the new icon). Also, I seem to be missing custom cursor for the god mode storage tool (not sure if intended or some bug).
Kindly see screenshots. 
Example of single selection of unity tool:
<img width="992" alt="Highlight of entity with tool cursor" src="https://github.com/Keranik/COI-Extended/assets/106548965/5abe3d21-8fd1-4423-b018-0989378a566e">

Missing custom tool cursor:
<img width="258" alt="Missing custom tool cursor" src="https://github.com/Keranik/COI-Extended/assets/106548965/2433e5c8-8f19-4628-93d1-0180273c032f">

**Comment by Keranik** [comment]
I'll look into this and get back to you when I have an answer, thanks for posting!

**Comment by Keranik** [comment]
This is in the next version, thanks.
