### ISSUE TITLE
The game won't let me save. Need a mod update.

### ISSUE THREAD

**Issue by AlexBig101** [Keranik/COI-Extended#19]
The game won't let me save. Need a mod update.
Yesterday everything was fine, today the game won't let me play. The game was updated to v0.6.1 and this mod no longer fits the game version??
![2024-04-11_142948](https://github.com/Keranik/COI-Extended/assets/87583353/a78fa3a3-9a89-4ef5-817c-75ffabcc1901)
![2024-04-11_143255](https://github.com/Keranik/COI-Extended/assets/87583353/58954e9d-6cc0-48fe-8c55-d95773a379da)

**Comment by Keranik** [comment]
Sorry to hear about your navigation issues, happy to hear you got it fixed.
