### ISSUE TITLE
Savefile for checking of Small Battery charge-discharge oddities

### ISSUE THREAD

**Issue by mrstoned-gh** [Keranik/COI-Extended#2]
[moddysave_24-02-22_20-35-14.zip](https://github.com/Keranik/COI-Extended/files/14388094/moddysave_24-02-22_20-35-14.zip)

**Comment by mrstoned-gh** [comment]
[24-02-22_18-47-10_7714.log](https://github.com/Keranik/COI-Extended/files/14388607/24-02-22_18-47-10_7714.log)
Also the log-file from the last session.
I'm finding references to the batterymanager in there atleast, been years since i did any coding but still could give usefull info.

**Comment by Keranik** [comment]
In the save file in question there is a battery bank next to a waste sorting plant and it is fully charged.

Possibly I could make the UI more clear?

![sbb](https://github.com/Keranik/COI-Extended/assets/137360086/7538fca3-d34d-4caa-8d4a-e22e8e17087f)

**Comment by mrstoned-gh** [comment]
Ohh, i didn't even connect with that.
For me capacity means contained volume (i do work with alot of fluids :)
Perhaps change Capacity to Stored Power? Or locally stored power vs network stored power?

Otherwise that mod i great. Increases the difficulty from basegame to an enjoyable level for me.
I have tested many resource-management games thruout the years.

Thanks.

**Comment by Keranik** [comment]
Probably a smart idea, will make sure it gets in the next update :)  Thanks for the feedback

**Comment by mrstoned-gh** [comment]
Another thought i just had, is the possibility to enable "only charge using surplus power" like many stock buildings do, electric boiler for example.
That would pair nice with solar arrays and not make it spin up backup diesel generators to charge the batteries is temporary powershortages.
