### ISSUE TITLE
Sea Wall (Corner)

### ISSUE THREAD

**Issue by LennyIndustries** [Keranik/COI-Extended#21]
Hi, the sea wall corner has 2 squares that collied with anything in the corner.
![afbeelding](https://github.com/Keranik/COI-Extended/assets/10868197/3fdf9d1f-a7cf-40ab-a0a5-b3e263ace7b3)
The other boxes are inside the wall, but the parts coming from the corner don't collide with anything.
![afbeelding](https://github.com/Keranik/COI-Extended/assets/10868197/d7fbe5a0-9027-4bac-b8d1-82061abdfd56)

**Comment by Keranik** [comment]
They were something that I made because I was trying to see if it was possible for me to make 3d models, since I'm not an artist.  I might go back to these at some point and do them properly in the future.  Thanks for letting me know about it.
