### ISSUE TITLE
Difficulty identifying trucks

### ISSUE THREAD

**Issue by DevelopmentAnything** [Keranik/COI-Extended#24]
Quiz

![image](https://github.com/Keranik/COI-Extended/assets/110871727/c2eddea3-df66-4c02-ac91-f31500ad85b7)

![image](https://github.com/Keranik/COI-Extended/assets/110871727/d08e07b6-113e-40e0-b148-ace05d518bd8)

Which car is TRUCK TRACTOR?

![image](https://github.com/Keranik/COI-Extended/assets/110871727/35fe081b-e938-4afa-a0ea-a49f896d9ef3)

Why isn't red?

🤔🤔🤔

**Comment by Keranik** [comment]
😆 I am working on a model for it, hopefully soon
