### ISSUE TITLE
Unknown event/action triggers maintenance requirement to a complete zero

### ISSUE THREAD

**Issue by lekkimsm2500** [Keranik/COI-Extended#27]
I've had this in multiple different games now. At some point along the session, for some unknown reason, nothing will no longer require any maintenance. It happens suddenly, and i suspect it happens in relation to SOMETHING in the cheat mod. I am not sure why. I am always sure that maintenance haven't been disabled in the cheat menu, i've tried turning it on and off but it doesn't seem to help. I've tried turning on and off edicts, that had any relation to maintenance, but that does not help either.

Two perfect examples, from two different games, of when it happens. It shows right away on the chart:

![Screenshot 2024-04-14 at 02-35-38 20240414022924_1 jpg (JPEG Billede 1920 × 1080 pixels) - Skaléret (84_)](https://github.com/Keranik/COI-Extended/assets/3638728/4b51c27b-8788-4f2a-addf-9c1be3818b9b)
![Screenshot 2024-04-14 at 02-35-25 20240414022643_1 jpg (JPEG Billede 1920 × 1080 pixels) - Skaléret (84_)](https://github.com/Keranik/COI-Extended/assets/3638728/06a454f9-d014-404e-a46f-f0ce89939a0c)

Another point of interest, is the chart overview does for example show that mega excavators doesn't use any maintenance:

![Screenshot 2024-04-14 at 02-35-56 20240414022932_1 jpg (JPEG Billede 1920 × 1080 pixels) - Skaléret (84_)](https://github.com/Keranik/COI-Extended/assets/3638728/bf355fc7-a5b9-4169-a3a6-c6d04d80367f)

However, clicking on a running mega excavator shows different information:

![Screenshot 2024-04-14 at 02-36-04 20240414022949_1 jpg (JPEG Billede 1920 × 1080 pixels) - Skaléret (84_)](https://github.com/Keranik/COI-Extended/assets/3638728/f236d8ea-375e-4cb7-81e4-84bcbc30c722)

It does show actual main. need/60t but that's all. The buffer on the same excavator does not deplete at all, after this strange event. 

I haven't got a clue as to what triggers it, i am not sure how to replicate it, so i'm hoping you might have a tiny idea what could be causing this.

Using extended, sink and cheat.

**Comment by Keranik** [comment]
Do you use the fill all maintenance buffers button?

**Comment by lekkimsm2500** [comment]
Not once in either of these two games, before or after the event. I've since tried loading both up when the event has occurred, and have tried all sorts of combinations of removing all/any main. depot, rebuilding them, turning off and on maintenance in the cheat menu and also having used the buffer cheat before and after said tries of things.

I haven't been able to replicate what suddenly triggers this maintenance glitch, or subsequently get the regular maintenance cycle back in working order post glitch.

**Comment by Keranik** [comment]
I appreciate your dedication to helping find the issue, and hope that we can find a way to reproduce it so that this error will not occur in the future!  Do not hesitate to file another issue if we can nail this down.
