### ISSUE TITLE
Unable to enter into contract

### ISSUE THREAD

**Issue by DevelopmentAnything** [Keranik/COI-Extended#28]
![image](https://github.com/Keranik/COI-Extended/assets/110871727/522462b5-82f2-41af-8c8c-afd8fd98487d)

map has been completely deformed.
Trade button is not active.
cheat mode is not used.

I want trade Gold - Oil.

**Comment by Keranik** [comment]
Can you attach save file please?

**Comment by DevelopmentAnything** [comment]
[20240406.zip](https://github.com/Keranik/COI-Extended/files/14995749/20240406.zip)
