### ISSUE TITLE
Disable fuel consumption cheat

### ISSUE THREAD

**Issue by Caspygh** [Keranik/COI-Extended#31]
Hello,
The "Disable fuel consumption" cheat deactivates after reloading a save.
Issue encountered using version 0.7.0a, base game version 0.6.2a. Installed whole COIExtended.AllMods, no other mods installed. Unsure about earlier versions.
Thank you.

**Comment by Caspygh** [comment]
Then it's weird because I also have deactivated the "use maintenance" and
that doesn't reset.

**Comment by Keranik** [comment]
From a player-facing perspective I can understand how it can be confusing that some things seemingly save and others do not.

This is just a function of how the game was developed though.  The maintenance toggle is stored in the maintenance manager, that is saved to the save file when the game is saved.

The fuel consumption management is handled in another manager that does not save the variable.  

The Cheat mod itself doesn't actually save or store any information, anything that is saved is done by the game itself as a function of how certain cheats are enabled.

**Comment by Caspygh** [comment]
Wow, thanks for the explanation. Makes perfect sense.
