### ISSUE TITLE
Failure to recognise install

### ISSUE THREAD

**Issue by TraumaticNutter** [Keranik/COI-Extended#32]
I have followed the install instructions, however the game hasn't recognised this. 
![20240420202549_1](https://github.com/Keranik/COI-Extended/assets/167647150/eb12d99e-7189-4084-81eb-6e02804bdac6)

**Comment by Keranik** [comment]
Show Mods folder

**Comment by TraumaticNutter** [comment]
![mods folder](https://github.com/Keranik/COI-Extended/assets/167647150/0cdda378-352b-4d6b-9dae-3806325cf73c)

**Comment by Keranik** [comment]
You have not installed the mod properly.  You should have /Mods/COIExtended/COIExtended.dll

**Comment by TraumaticNutter** [comment]
I am extracting the zip file into the mods folder. there isn't a .dll file within the zip. I dont understand what i am doing wrong

**Comment by Keranik** [comment]
You are extracting the .zip file and also creating a new directory that should not be there.

All .zip files come with the directory as the base, you need to "Extract here" and not "Extract here as" or whatever is similar for the program you are using to extract.

You should have %appdata%/Captain Of Industry/Mods/COIExtended/COIExtended.dll if you have installed properly.
