### ISSUE TITLE
No surrounding villages

### ISSUE THREAD

**Issue by DevelopmentAnything** [Keranik/COI-Extended#38]
There should be at least one nearby
It became a really boring mode.

![image](https://github.com/Keranik/COI-Extended/assets/110871727/e113a808-4b0c-4e43-9c7b-134fea444d0f)

or....am I unlucky?

**Comment by Keranik** [comment]
It looks like you just made an extremely large map and you haven't found any yet.  

Save the game.... open the world map, type **tomato** in console to reveal all map if you want, then load old game.
