### ISSUE TITLE
No upgrade button

### ISSUE THREAD

**Issue by DevelopmentAnything** [Keranik/COI-Extended#39]
![image](https://github.com/Keranik/COI-Extended/assets/110871727/16021291-2caa-442b-8900-0db7bc45fd65)

![image](https://github.com/Keranik/COI-Extended/assets/110871727/156baf56-9412-4390-965d-0275a29e5c70)

Upgrade to LV2 without building reconstruction

**Comment by Keranik** [comment]
I can add for water pump, cannot add for ore sorter... maybe next patch!

**Comment by DevelopmentAnything** [comment]
![image](https://github.com/Keranik/COI-Extended/assets/110871727/5feb5a61-3aed-4f1c-a85c-d109b5382441)

Storage III -> IV -X-> V


![image](https://github.com/Keranik/COI-Extended/assets/110871727/da5e58b7-ccb3-45ec-ae19-859534c27f5d)

Storage IV -O-> V

Do not delete the issue before the resolved release is uploaded.
