### ISSUE TITLE
World map generation

### ISSUE THREAD

**Issue by reklrekl** [Keranik/COI-Extended#41]
I've explored every location on the world map, but I didn't find any sugar cane or poppy seeds.
Also I only found 2 cargo ships.

I have no Idea what world generation settings I had or how to access them...
Is there any way to "fix" this issue? I'm 600y into the save and wouldn't want to start over.
Thanks!
<img width="796" alt="COIE_screenshot" src="https://github.com/Keranik/COI-Extended/assets/4126734/8a0f6c3f-7b9b-4c9d-a5e7-6e0bf761a0f7">

**Comment by Keranik** [comment]
unlock_all_map_tech

Access console by pressing ` on English-US keyboard and type in the above command.

There are only supposed to be 2 cargo ships, because you can build your own!
