### ISSUE TITLE
Documention Request

### ISSUE THREAD

**Issue by 0rangeChicken** [Keranik/COI-Extended#5]
Hello there. With the expanding scope of the mod, I feel like documentation on the various mechanics would be useful. There are some unique mechanics in this mod, and these are not really explained in game. For example: the modded ores not generating on the home map because they are found on the world map. That wasn't clear, and I thought my game save may have been messed up until I went to discord to clarify. 

I feel a wiki here on Github, or more information in game, would help with this.

**Comment by Keranik** [comment]
This will be coming in the next update after Update 2 is released!
