### ISSUE TITLE
cargoship: drydock

### ISSUE THREAD

**Issue by A-Dunois** [Keranik/COI-Extended#50]
Hello,

With version 0.7.7 and 0.7.5, after a reloading the cargoship drydock (primitive and normal) disappear. 
All icon (paused, breakdown, ..) remain

I try with my current game and a newgame.

![image](https://github.com/Keranik/COI-Extended/assets/71859923/b5c06874-a702-48a9-bf85-ef5dd4a4da87)

**Comment by Keranik** [comment]
Fixed in 78

**Comment by A-Dunois** [comment]
Thanks, it's work fine.
