### ISSUE TITLE
Iron Ore gets Deleted

### ISSUE THREAD

**Issue by killerwowlf** [Keranik/COI-Extended#59]
when i start a game with this mod all iron ore gets replaced with crushed iron ore.
this means i cant play the came.
hope i didnt do something wrong.

**Comment by Keranik** [comment]
This happens because of the Terrain cache that was added in one of the recent updates.  You need to find the terrain cache related to the map you are playing (it's in the same folder as the Saves directory) and delete it so that the mod can generate its own terrain cache.
