### ISSUE TITLE
When clicking on a Food Market the overlay does not appear

### ISSUE THREAD

**Issue by angusmaul** [Keranik/COI-Extended#6]
Clicking on an existing Food Market or creating a new Food Market unable to access the overlay

Note: Was using the COIExtended mods, but loading with Mods disabled does not resolve the issue.
![2024-04-06_07-45-58](https://github.com/Keranik/COI-Extended/assets/1232390/9df2d4ad-4c06-4448-99f0-a47dee90c822)

This works when loading a save without COI mods enabled.

Reloading a game that had these mods enabled does not resolve the issue.

Its game breaking if you cant setup more Food Markets

**Comment by LumberingTroll** [comment]
Im not having this issue with the latest build.

**Comment by DevelopmentAnything** [comment]
me too.
latest build have problem.

**Comment by Keranik** [comment]
COI:Extended is not officially compatible with saved games, only as recently as a few hours ago was a build put out that has fixed some of the major issues and -might- be compatible with saved games.  If you are having issues on the latest build, please let me know.

**Comment by angusmaul** [comment]
Closing bug
