### ISSUE TITLE
very little space for fishing dock

### ISSUE THREAD

**Issue by DevelopmentAnything** [Keranik/COI-Extended#8]
![image](https://github.com/Keranik/COI-Extended/assets/110871727/3463d277-03e4-4a50-8dcc-26cc66fa2fb5)
Unable to install on top of soil.

![image](https://github.com/Keranik/COI-Extended/assets/110871727/b24568dc-1c6a-47ea-88c1-7648b08cf416)

Can you relax the terrain conditions?

**Comment by Keranik** [comment]
Fixed in next patch, thanks!

**Comment by DevelopmentAnything** [comment]
@Keranik 
I used the 061 registered recently
Even what was installed in the second picture became impossible.
It's impossible to build at all.

The conditions are too demanding.
I'd like to know how to use it.

**Comment by Keranik** [comment]
I understand now you mean the constraints on the terrain, I have fix for
next patch.

**Comment by Keranik** [comment]
I updated the release page with a 061dllpatch that should fix this issue, I can't do anything else until the official mod tools get updated as I can't manipulate asset packs at the moment.
